[device]
DEVICE_NAME = "akita"
'GRAPHENEOS[UPDATE_CHANNEL]' = "stable"
'MAGISK[PREINIT]' = "sda10"
ADDITIONALS[ROOT] = true
CLEANUP = true
[device]
DEVICE_NAME = "lynx"
'GRAPHENEOS[UPDATE_CHANNEL]' = "stable"
'MAGISK[PREINIT]' = "sda8"
ADDITIONALS[ROOT] = true
CLEANUP = true
